name = "JMC MTR Lets Play Server"
author = "Jake Vento (JMC Team)"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dd12dbe25de07c61d57796d1a9642f33353b6953c303cc5c7a5aea1c5854fc82"

[versions]
fabric = "0.16.10"
minecraft = "1.19.2"
