name = "JMC MTR Lets Play Server"
author = "Jake Vento (JMC Team)"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "182c3a50de8397d769fb6e4b32dbfb1db83611f77dba796822bbb35723d429ea"

[versions]
fabric = "0.16.10"
minecraft = "1.19.2"
