name = "JMC MTR"
author = "JV-LAB-CREATE"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "570b86634f69c5f63b688d66d403cb3960594757cd4982f6cc5885e98e9d7f45"

[versions]
fabric = "0.19.2"
minecraft = "1.20.4"
