name = "JMC MTR"
author = "JV-LAB-CREATE"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7aec4f4d9bfd212e50b177854efd779295f05bae97ed5b5d18a15b15d62fab68"

[versions]
fabric = "0.19.2"
minecraft = "1.20.4"
