name = "JMC MTR"
author = "JV-LAB-CREATE"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c7e4d492efcc49487d127157e361de75fda21a122ec4b3d054bdf22080ba2a8a"

[versions]
fabric = "0.17.0"
minecraft = "1.20.4"
