name = "JMC MTR Lets Play Server"
author = "Jake Vento (JMC Team)"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e2379454c226002dd981177db019bb45f4081eaa6d03be6d4cb2d87d53907b3b"

[versions]
fabric = "0.16.10"
minecraft = "1.19.2"
