name = "JMC MTR Lets Play Server"
author = "Jake Vento (JMC Team)"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d1d0d461e0dbf208314dadfac8f66503c6b7d3fdb32a81bdc55fa016923b6c7"

[versions]
fabric = "0.16.10"
minecraft = "1.19.2"
