name = "JMC MTR Lets Play Server"
author = "Jake Vento (JMC Team)"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "17ccb4949c62ef15229b9701fa324ad14d4d878c7952fa74605f6f301d758d8f"

[versions]
fabric = "0.16.10"
minecraft = "1.19.2"
