name = "JMC MTR Lets Play Server"
author = "Jake Vento (JMC Team)"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4180d578588082b1661d9db8056e58d0773bf63a92b5b1bd38f822d446a7a0f0"

[versions]
fabric = "0.16.10"
minecraft = "1.19.2"
