name = "JMC MTR Lets Play Server"
author = "Jake Vento (JMC Team)"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "24f188afb166264f02e1c3ae52052bfd4d1097b2d66265b4045cff6bde9bf54f"

[versions]
fabric = "0.16.10"
minecraft = "1.19.2"
