name = "JMC MTR"
author = "JV-LAB-CREATE"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb581ecf87d88c92aa12f48a6b1336ff7fa04ad16c35b7ef80ba2c06ea85186d"

[versions]
fabric = "0.19.2"
minecraft = "1.20.4"
