name = "JMC MTR Lets Play Server"
author = "Jake Vento (JMC Team)"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "764ddd98199589dfa7b949e5ac4ab443833fe387e052f69f27bf3437eff3cf79"

[versions]
fabric = "0.16.10"
minecraft = "1.19.2"
