name = "JMC MTR Lets Play Server"
author = "Jake Vento (JMC Team)"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3867cda1c1521941c8d12966298049b5eeee6a44e69e4c94dab59524371678fb"

[versions]
fabric = "0.16.10"
minecraft = "1.19.2"
